export {default as Sichtbetontreppen } from "./Sichtbetontreppen.jpeg";
export {default as baustellensohle } from "./baustellensohle.jpg";
export {default as schalungsbauer } from "./schalungsbauer.jpg";
export {default as maurerarbeiten } from "./maurerarbeiten.jpg";
export {default as mini_bagger_garten} from "./mini-bagger-garten.jpg";
export {default as Baustellenplanung} from "./Baustellenplanung.jpg";
export {default as building_1} from "./building-1.jpeg";
export {default as building_2} from "./building-2.jpeg";
export {default as building_3} from "./building-3.jpeg";
export {default as building_4} from "./building-4.jpeg";
export {default as building_5} from "./building-5.jpeg";
export {default as building_6} from "./building-6.jpeg";
export {default as gartengestaltung} from "./gartengestaltung.jpg";
export {default as building_8} from "./building-8.jpeg";
export {default as traumhaus} from "./traumhaus.jpg";
export {default as rohbau} from "./rohbau.jpg";
export {default as nachhalitigkeit} from "./nachhalitigkeit.jpg";
export {default as qualitätbauen} from "./qualitätbauen.jpg";
export {default as innovativesbauen} from "./innovativesbauen.jpg";